---
- name: Ensure group "panda" exists.
  ansible.builtin.group:
    name: panda
    state: present

- name: Add the user 'panda' with a bash shell, appending the group 'panda' and 'sudo' to the user's groups.
  ansible.builtin.user:
    name: panda
    shell: /bin/bash
    groups: panda,sudo
    append: yes

- name: Copy `authorized_keys` file from vagrant user to panda user.
  ansible.posix.authorized_key:
    user: panda
    state: present
    key: "{{ lookup('file', '/home/vagrant/.ssh/authorized_keys') }}"
